### PR TITLE
adding libjemalloc2 to docker images

### LINKED ISSUE #128: libjemalloc2 package missing
Hello,

using the latest image available (v1.0.72), it will be nice to have `libjemalloc2` package installed.
It seems missing, here the warning message:
```
WARN  [main] 2023-01-22 17:49:47,191 StartupChecks.java:143 - jemalloc shared library could not be preloaded to speed up memory allocations
```
A small update in Dockerfiles at "apt install" command will be perfect:
 `apt install curl unzip iproute2 libaio1 -y` to  `apt install curl unzip iproute2 libaio1 libjemalloc2 -y`

Thanks for your help

### PR DESCRIPTION
**Pull request by jeffreyscarpenter**
Fixes #128 

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

**Comment by tatu-at-datastax** [comment]
As per our discussion, this is good but didn't it need additional configuration in startup scripts?

**Review by tatu-at-datastax — APPROVED** [review]

**Comment by jeffreyscarpenter** [comment]
> As per our discussion, this is good but didn't it need additional configuration in startup scripts?

yes, but the change needed is to the `starctl` script which will require PR on `stargate` repo.

**Comment by tatu-at-datastax** [comment]
> > As per our discussion, this is good but didn't it need additional configuration in startup scripts?
> 
> yes, but the change needed is to the `starctl` script which will require PR on `stargate` repo.
> 
> [stargate/stargate#2404](https://github.com/stargate/stargate/pull/2404)

Ah. Sorry, missed the repo this was for.

**Review by tatu-at-datastax — APPROVED** [review]

**Comment by ivansenic** [comment]
will this also be copied to the https://github.com/stargate/stargate/blob/main/coordinator/Dockerfile?

**Comment by jeffreyscarpenter** [comment]
> will this also be copied to the https://github.com/stargate/stargate/blob/main/coordinator/Dockerfile?

yes, #2402

**Pull request merged**
